services:
  # Development Service
  dev:
    build:
      context: ./frontend
      dockerfile: ../.docker/Dockerfile.dev
    container_name: shop-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true # Essential for Windows hot reload

  api:
    build:
      context: ./backend
      dockerfile: ../.docker/Dockerfile.api
    container_name: shop-api
    ports:
      - "8080:8080"
    restart: unless-stopped
  # Production Test Service (Optional, commented out)
  # prod:
  #   build:
  #     context: ./frontend
  #     dockerfile: ../.docker/Dockerfile.prod
  #   container_name: shop-prod
  #   ports:
  #     - "8080:80"
