services:
  # Development Service
  dev:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    container_name: shop-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true # Essential for Windows hot reload
    
  api:
    build:
      context: ./mock-server
      dockerfile: Dockerfile
    container_name: shop-api
    ports:
      - "8080:8080"
    restart: unless-stopped

  # Production Test Service (Optional, commented out)
  # prod:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: shop-prod
  #   ports:
  #     - "8080:80"
